[package]
name = "polywal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.8"
confy = "0.5.1"
home = "0.5.4"
owo-colors = "3.5.0"
serde = { version = "1.0.154", features = ["derive"] }
